version: 2
updates:
  - package-ecosystem: gomod
    directory: /session-manager
    schedule:
      interval: weekly
    groups:
      go-deps:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - /session-manager
      - /df-image-base
      - /df-image-sdl
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
