#!/bin/sh
# Wait for Xvfb to create its socket before starting VNC.
until [ -S /tmp/.X11-unix/X0 ]; do sleep 0.2; done
exec x11vnc \
    -display :0 \
    -forever \
    -shared \
    -nopw \
    -rfbport 5900 \
    -noxdamage \
    -noipv6 \
    -quiet 2>&1
