#!/bin/sh
# Wait for Xvfb to be ready.
until xdpyinfo -display :0 >/dev/null 2>&1; do sleep 0.2; done
exec x11vnc \
    -display :0 \
    -forever \
    -shared \
    -nopw \
    -rfbport 5900 \
    -noxdamage \
    -noipv6 \
    -quiet 2>&1
